"""add updated_on column to job table

Revision ID: db13dca6d858
Revises: ed8bfc5cd6a7
Create Date: 2025-06-25 20:27:05.778763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db13dca6d858'
down_revision: Union[str, Sequence[str], None] = 'ed8bfc5cd6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('jobs', 'max_attempts')
    op.drop_column('jobs', 'retry_attempts')
    op.drop_column('jobs', 'backoff_multiplier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('backoff_multiplier', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('retry_attempts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('max_attempts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'updated_on')
    # ### end Alembic commands ###
